---
abstract: 'upload images to imgur.com'
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120630'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Imgur
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  JSON: 0
  LWP: 0
  MIME::Base64: 0
version: 0.03
