---
abstract: 'upload images to imgur.com via deprecated version 2 API'
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Imgur
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  JSON: 0
  LWP: 0
  MIME::Base64: 0
resources:
  bugtracker: https://github.com/benkasminbullock/WWW-Imgur/issues
  repository: https://github.com/benkasminbullock/WWW-Imgur
version: 0.04
